# THIS FILE IS OUT OF BOUNDS

language: python
python:
  - "3.5"
script:
  - ./validate-on-master.sh
branches:
  only:
    - master
git:
  depth: false
notifications:
  email:
    on_success: never
    on_failure: always
